### ISSUE TITLE
Why over-complicating simple things?

### ISSUE THREAD

**Issue by MacKentoch** [vonovak/react-navigation-header-buttons#27]
All that code just for a button???:

```javascript
import * as React from 'react';
import MaterialIcons from 'react-native-vector-icons/MaterialIcons';
import HeaderButtons, { HeaderButton, Item } from 'react-navigation-header-buttons';

// define IconComponent, color, sizes and OverflowIcon in one place
const MaterialHeaderButton = props => (
  <HeaderButton {...props} IconComponent={MaterialIcons} iconSize={23} color="blue" />
);

export const MaterialHeaderButtons = props => {
  return (
    <HeaderButtons
      HeaderButtonComponent={MaterialHeaderButton}
      OverflowIcon={<MaterialIcons name="more-vert" size={23} color="white" />}
      {...props}
    />
  );
};
export const Item = HeaderButtons.Item;
```

This is non sense...

**Comment by vonovak** [comment]
Hi @MacKentoch and thanks for the comment :)
The code you pasted is a one-time setup that defines how things are going to look. The buttons are then defined in a more simple way, as documented in the Readme. 
The api is indeed a little more verbose than I'd like it to be, but it's not something that I consider a huge deal for me. All the configurations stem from real needs that I have.

If you have any ideas for improvement, I'll be happy to hear them out, but I also possible that the current implementation does not leave too much space for improvement. If you wanna create your library to solve the same problem, I'll be very curious to see how you designed it. Please let me know if you do that. Thanks.

**Comment by MacKentoch** [comment]
No offense.
I appreciate you have sense of humour, that is nice.

I won't create such a library simply because: **there is no need as this is nearly absurd!**

This is just a `basic RN Touchable` with `style` and a child as a `Text` or `any Icon component`.
*So reading README (*even well written that is not the question*) takes far more time than implementing our own button.*

*Wouldn't you find that creating a library to implement a function `add` is absurd as JS `+` does far better job?*

**I think RN community is wasting too much precious time where it is not needed (*at least until the most important is done*).**

**Comment by vonovak** [comment]
>This is just a basic RN Touchable with style and a child as a Text or any Icon component.

That's correct, and I guess we can agree that a navbar button, in essence, does not need any more than that.

> So reading README takes far more time than implementing our own button.

You will be able to implement a button faster than going through the Readme setup, but you'll soon find out that its margins from the screen edge or from other buttons need some tweaking in order to look like in other native apps. Then you'll notice the "correct margins" are different per-platform of course, and you'll likely spend more time than you think tweaking these to make your buttons look like in a native app. I have done the work here so you don't have to.

That's what I have done at the start. Then I had more requirements:
- having some buttons visible and some in the overflow menu 
- defining what the overflow menu looks like and what should happen when user presses it
- easy support for text buttons and icons from react native vector icons, without depending on the package 
- disabled state and custom styles for it
- rendering buttons conditionally
... 

Before long, I created several files to do this. They are not complicated and there are just three of them, but I do believe that distributing them in a package may help others, and so I did that. 

To compare this with adding numbers is imho an oversimplification. Perhaps you now see why some parts may look more difficult than expected.
