### ISSUE TITLE
Make the title attribute actually required

### ISSUE THREAD

**Issue by alexsegura** [vonovak/react-navigation-header-buttons#66]
Hi. 

Thank you for this library 🙂 

When not setting a `title` prop on `Item` or `HiddenItem`, we get the well-know "each child in a list should have a unique key" error. 

This is because `HeaderButtons` is using `title` as key.

Is it possible to enforce the presence of this prop explicitly? 
Like with `prop-types`? 

Thanks

**Comment by vonovak** [comment]
hello, I'd prefer avoiding prop-types. I prefer static analysis, ie. Flow or Typescript. If you're using those, I think you should get an error if you do not specify title

**Comment by alexsegura** [comment]
I'm not using TypeScript. 

Are really TypeScript and prop-types the same thing, and serving the same purpose?
The problem here is the error is not explicit, the error should clearly indicate what's wrong. 
Maybe there's something missing in your TypeScript to mark the prop as required? I don't know.

**Comment by vonovak** [comment]
> I'm not using TypeScript.

if you're not using typescript, then the flow and TS definitions shipped with the library will not help;

> Are really TypeScript and prop-types the same thing, and serving the same purpose?

my point is that prop types are a runtime check, while TS is a static check - you'll get the missing title prop error even without running any of the code. With prop types you need to run the code to get a warning.

> The problem here is the error is not explicit, the error should clearly indicate what's wrong.

it's true that this could be better, but the error is well-known and easy to fix even for a beginner imho. I do not want to add prop types now because I'm in the middle of a rewrite, and even when I'm done I do not want to maintain flow, typescript AND prop-types.  Even core RN repo is removing prop types. My advice - use typescript :)

**Comment by vonovak** [comment]
i'm closing this as answered, thanks
